Refactor IncidentPredictor architecture
antijob/neuro-parser pull request #229
Opened 2024-08-26 13:02 UTC by SahDoum

2024-08-31 10:11 UTC, Vldln approved these changes

2024-09-02 11:20 UTC, Vldln requested changes

2024-09-02 12:09 UTC, SahDoum commented on server/libs/handler.py
> +            raise TypeError(f"{handler_class.__name__} must be a subclass of 'Handler'")
Ну это пайланс так говорит, но ничего не мешает попытаться зарегистрировать любой класс. Стоит проверять, что этого не происходит

2024-09-02 12:25 UTC, SahDoum commented on server/libs/handler.py
> +            if handler_class.can_handle(*args, **kwargs):
Поправил

2024-09-02 17:37 UTC, katsorio commented on server/core/incident_predictor/predictors/bert.py
> +            return True
Здесь, если чисто докопаться, возвращается или `None` или `True`.

2024-09-02 17:38 UTC, katsorio commented on server/core/incident_predictor/predictors/bert.py
> +                raise FileNotFoundError(
@Vldln если нет предиктора, но путь до модели есть -- это нештатная ситуация, надо кидать исключение? Или это значит, что следующий предиктор должен прочекать?

2024-09-02 17:41 UTC, katsorio commented on server/libs/handler.py
> +    def can_handle(self, *args, **kwargs) -> bool:
Это классметод или метод? В списках `HandlerRegistry` указан список классов, наверное, тогда и здесь стоит добавить `@classmethod` декоратор: 
```
   @classmethod
   @abstractmethod
   def can_handle(cls, *args, **kwargs) -> bool:
```

2024-09-03 12:45 UTC, katsorio commented on server/libs/handler.py
> +    def can_handle(self, *args, **kwargs) -> bool:
Да я тоже думаю, что пусть будет классметод

2024-09-03 12:56 UTC, katsorio commented on server/core/source_parser/source_parser.py
> +    registry = HandlerRegistry[ParserBase]()
Мб сделать `__init__(self, *handlers: Type[Handler[T]])` для `HandlerRegistry` и парсеры в аргументы засунуть?

2024-09-03 15:17 UTC, merged